#!/bin/bash
if [ x$EDITOR = x ]; then
   if which vim>/dev/null; then
       EDITOR=vim
   else
       EDITOR=vi
   fi
fi

HOWTODIR=~/.howto
if [ ! -e $HOWTODIR ]; then
    mkdir $HOWTODIR
    ln -s ~/workspace/howto/notes.txt $HOWTODIR
fi
$EDITOR $HOWTODIR/notes.txt
